version: 0.2

phases:
  install:
    runtime-versions:
      docker: 19
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 &
      - sleep 60
  build:
    commands:
      - docker build -t image_python -f test_files/python .
      - docker build -t image_openjdk -f test_files/openjdk .
