version: 0.2

phases:
  install:
    commands:
      - whoami
      - apt-get update -y
      - apt-get install apt-transport-https -y && apt-get update
      - apt-get install ca-certificates -y && apt-get update
      - apt-get install curl gnupg lsb-release -y
      - curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o docker-archive-keyring.gpg
      - cat docker-archive-keyring.gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
      - echo "" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      - echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu" | sudo tee /etc/apt/soruces.list.d/docker.list
      - echo "$(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      - apt-get update -y
      - apt-get install docker-ce docker-ce-cli containerd.io -y
  build:
    commands:
      - docker build -t image_python -f test_files/python .
      - docker build -t image_openjdk -f test_files/openjdk .
