version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      - docker pull python:3.5
      - docker pull openjdk:latest
  build:
    commands:
      - docker build -t image_python -f test_files/python .
      - docker build -t image_openjdk -f test_files/openjdk .
