version: 0.2

phases:
  install:
    runtime-versions:
      docker: 19
    commands:
      - sleep 60
  build:
    commands:
      - docker build -t image_python -f test_files/python .
      - docker build -t image_openjdk -f test_files/openjdk .
      - docker run image_python